[package]
name = "ejit-evm"
version = "0.1.0"
edition = "2024"

[dependencies]
# ejit = { path = "../ejit" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[dev-dependencies]
reqwest = { version = "0.12.15", features = ["blocking"] }
